name: graficas_sumasRieman
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - tk
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxt
  - xorg-xauth
  - xorg-xextproto
  - xorg-xproto
  - xvfbwrapper
